### ISSUE TITLE
pro4j.min.js文件缺失

### ISSUE THREAD

**Issue by tcm1192478634** [vjmap/vjmap-playground#1]
Failed to load resource: the server responded with a status of 404 (Not Found)
Refused to execute script from 'http://127.0.0.1:8080/js/proj4.min.js' because its MIME type ('text/html') is not executable, and strict MIME type checking is enabled.
09baiduCadLayer.js:280 Error: Script failed to load.
../../js/proj4.min.js
    at HTMLScriptElement.<anonymous> (vjmap.min.js:9:183141)

![image](https://github.com/vjmap/vjmap-playground/assets/40083798/f0947926-50e2-4079-a8e3-f3c1e7ddc2d3)

**Comment by 53356454** [comment]
已增加proj4.min.js文件

**Comment by vjmap** [comment]
已增加pro4j.min.js

**Comment by vjmap** [comment]
已增加pro4j.min.js
