### ISSUE TITLE
请问例子中的“解锁全部按钮”怎么没有效果？

### ISSUE THREAD

**Issue by front-end-fan** [vjmap/vjmap-playground#2]

**Comment by front-end-fan** [comment]
https://vjmap.com/app/visual/#/draw?mapid=cf64f9ebb5dc&version=v2&mapopenway=GeomRender&theme=dark

**Comment by vjmap** [comment]
经测试没问题。先得选中一个对象锁定，锁定后对象将不能选中不能编辑。解锁全部才可以选中编辑。
